---
title: "Computational Archaeology"
subtitle: "01 - Introduction"
author: "Martin Hinz"
institute: "Institut für Archäologische Wissenschaften, Universität Bern"
fontsize: 9pt
date: "18/09/19"
output:
  xaringan::moon_reader:
    chakra: "../libs/remark-latest.min.js"
    css: ["../libs/default.css", "../libs/default-fonts.css", "../libs/customize.css"]
    lib_dir: "libs"
    seal: false
    nature:
      beforeInit: "../libs/macros.js"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      fig_caption: yes
      ratio: "16:10"
---
class: title-slide, center, middle
```{r, echo = FALSE}
# https://stackoverflow.com/questions/25646333/code-chunk-font-size-in-rmarkdown-with-knitr-and-latex
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r, echo = FALSE, results="asis"}
cat('# ', rmarkdown::metadata$title)
```

```{r, echo = FALSE, results="asis"}
cat('## ', rmarkdown::metadata$subtitle)
```

```{r, echo = FALSE, results="asis"}
cat('### ', rmarkdown::metadata$author)
```

```{r, echo = FALSE, results="asis"}
cat('#### ', rmarkdown::metadata$institute)
```

```{r, echo = FALSE, results="asis"}
cat(rmarkdown::metadata$date)
```

---

## Schedule

```{r echo=FALSE}
library(magrittr)
library(kableExtra)
schedule <- c(
  "18/09/19", "Introduction", "",
  "25/09/19", "General Aids", "",
  "02/10/19", "Data Bases I", "3",
  "09/10/19", "Data Bases II", "4",
  "23/10/19", "Visualisation I", "5",
  "30/10/19", "Visualisation II","7",
  "06/11/19", "Basic Statistics", "5, 6, 14",
  "13/11/19", "14C Calibration I", "6",
  "20/11/19", "14C Calibration II", "8",
  "27/11/19", "GIS I", "11",
  "04/12/19", "GIS II", "13",
  "11/12/19", "Digital (Field) Recording", ""
)
schedule <- as.data.frame(matrix(schedule,ncol=3, byrow = T))
colnames(schedule) <- c("date", "topic", "chapt. Shennan")
knitr::kable(schedule)  %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                latex_options = "striped",
                full_width = T)
```
